export enum AppTypes {
  OPEN_MODAL = 'APP/OPEN_MODAL',
  HIDE_MODAL = 'APP/HIDE_MODAL',
  FINISH_DIRECTION = 'APP/FINISH_DIRECTION',
  SHOW_SNACKBAR_ERROR = 'APP/SHOW_SNACKBAR_ERROR',
  HIDE_SNACKBAR_ERROR = 'APP/HIDE_SNACKBAR_ERROR'
}
