export enum SkillsTypes {
  FETCH_SKILLS = 'SKILLS/FETCH_SKILLS',
  FETCH_DIRECTIONS = 'SKILLS/FETCH_DIRECTIONS',
  UPDATE_DIRECTIONS = 'SKILLS/UPDATE_DIRECTIONS',
  SHOW_SKILLS = 'SKILLS/SHOW_SKILLS',
}
